version: "3.9"
services:
  postgres:
    image: postgres
    networks:
      - basic-server-net
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - service-data:/var/lib/postgresql/data
      # copy the sql script to create db & table
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: pg_isready -U postgres
  basic-go-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: basic-go-server
    container_name: basic-go-server
    networks:
      - basic-server-net
    ports:
      - 8080:8080
    env_file:
      - ./config/container.env
    depends_on:
      postgres:
        condition: service_healthy
networks:
  basic-server-net:
    name: basic-server-network
volumes:
  service-data:
    driver: local
